<a href="https://colab.research.google.com/github/Secatorrez/Secatorrez.github.io/blob/master/kawalki_na_boku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
def my_function(*kids):
	ile = len(kids)
	#print(ile)
	print("The youngest child is " + kids[ile-1])

my_function("Emil", "Tobias", "Linus", "Najmlodszy")

The youngest child is Najmlodszy


In [ ]:
# tescik array z numpy i zamiana w macierz
import numpy as np
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])
amatrix = np.block([[a1], [a2], [a3]])
print(amatrix)
print(amatrix[0])
print(amatrix[1])
print(amatrix[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


**TTTTT**